hospital.id=${HOSPITAL_ID:hosp-local-dev}

dynamodb.table.triagem=${DYNAMODB_TABLE_TRIAGEM:triagem-local}
quarkus.dynamodb.aws.region=${AWS_REGION:us-east-1}
quarkus.dynamodb.aws.credentials.type=default

sqs.queue.painel.url=${SQS_PAINEL_URL:http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/painel-queue}
quarkus.sqs.aws.region=${AWS_REGION:us-east-1}
quarkus.sqs.aws.credentials.type=default

%dev.quarkus.dynamodb.endpoint-override=http://localhost:4566
%dev.quarkus.sqs.endpoint-override=http://localhost:4566
%dev.sqs.queue.classificacao.url=http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/classificacao-queue

quarkus.http.port=8081
%dev.quarkus.lambda.mock-event-server.dev-port=8086
quarkus.lambda.handler=classificacao
quarkus.log.level=INFO
quarkus.log.category."br.gov.sus".level=DEBUG
quarkus.log.console.json=true
