hospital.id=${HOSPITAL_ID:hosp-local-dev}

dynamodb.table.triagem=${DYNAMODB_TABLE_TRIAGEM:triagem-local}
quarkus.dynamodb.aws.region=${AWS_REGION:us-east-1}
quarkus.dynamodb.aws.credentials.type=default

sqs.queue.nacional.url=${SQS_NACIONAL_URL:http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/nacional-queue}
quarkus.sqs.aws.region=${AWS_REGION:us-east-1}
quarkus.sqs.aws.credentials.type=default

%dev.quarkus.dynamodb.endpoint-override=http://localhost:4566
%dev.quarkus.sqs.endpoint-override=http://localhost:4566
%dev.quarkus.lambda.mock-event-server.dev-port=8087

quarkus.http.port=8082
quarkus.lambda.handler=consolidador
quarkus.log.level=INFO
quarkus.log.console.json=true
