hospital.id=${HOSPITAL_ID:hosp-local-dev}

dynamodb.table.conexoes=${DYNAMODB_TABLE_CONEXOES:conexoes-local}
dynamodb.table.triagem=${DYNAMODB_TABLE_TRIAGEM:triagem-local}
quarkus.dynamodb.aws.region=${AWS_REGION:us-east-1}
quarkus.dynamodb.aws.credentials.type=default

# URL do endpoint WebSocket (ex: https://XXXX.execute-api.us-east-1.amazonaws.com/prod)
ws.endpoint.url=${WS_ENDPOINT_URL:http://localhost:4566}

%dev.quarkus.dynamodb.endpoint-override=http://localhost:4566

# SQS (needed for dev-mode polling)
quarkus.sqs.aws.region=${AWS_REGION:us-east-1}
quarkus.sqs.aws.credentials.type=default
%dev.quarkus.sqs.endpoint-override=http://localhost:4566
%dev.sqs.queue.painel.url=http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/painel-queue

# CORS (allow frontend dev server)
%dev.quarkus.http.cors=true
%dev.quarkus.http.cors.origins=http://localhost:3000

# A Lambda WS-handler recebe eventos do API Gateway diretamente
# A Lambda sqs-fanout recebe eventos do SQS
quarkus.http.port=8084
%dev.quarkus.lambda.mock-event-server.dev-port=8085
quarkus.lambda.handler=ws-handler
quarkus.log.level=INFO
quarkus.log.category."br.gov.sus".level=DEBUG
quarkus.log.console.json=true
